feat: update cert-manager crd to v1.0
kubernetes-sigs/kubebuilder pull request #1667
Opened 2020-09-08 09:27 UTC by MartinForReal

Signed-off-by: MartinForReal <fanshangxiang@gmail.cn>
Fixed: #1666 

Migrate cert-manager related CR to v1

2020-09-08 09:48 UTC, MartinForReal commented
/check-cla

2020-09-08 09:58 UTC, MartinForReal commented
/assign @droot

2020-09-08 22:20 UTC, camilamacedo86 commented on pkg/plugin/v2/scaffolds/internal/templates/kustomize.go
> +#    version: v1
The `pkg/plugin/v2` ought to receive only fix bugs and cannot have breaking changes. All improvements and etc needs to be addressed only  in `pkg/plugin/v3`. Could you please update it?

2020-09-08 22:23 UTC, camilamacedo86 requested changes
Really thank you for your contribution. 🥇  Just a few nits:

- Note that The pkg/plugin/v2 ought to receive only fix bugs and cannot have breaking changes. All improvements and etc needs to be addressed only in pkg/plugin/v3. Could you please update it?
- Also, note that it is not passing in the testdata. After change the templates we need to run `make generate` it will re-generate the testdata
- Could you please add (v3 only) in the title as well? 

PS.: the commits need to be squashed.

2020-09-09 02:50 UTC, MartinForReal commented
I've changed the commit accordingly. FYI @camilamacedo86 Thanks!

2020-09-09 09:08 UTC, camilamacedo86 commented
Hi @MartinForReal, 

It shows great. See that it is not passing in the check to verify if the testdata/ samples are updated. See: https://travis-ci.org/github/kubernetes-sigs/kubebuilder/jobs/725451668#L1003-L1038

To update these samples we run `make generate`. Any change on the templates requires we run this command to do the pr. Could you please check it? Also, could you please add on the title (v3+ only)? And we need to start to use : 


```Contributors:

All code PR must be labeled with 🐛 (patch fixes), ✨ (backwards-compatible features), or ⚠️ (breaking changes)
Breaking changes will find their way into the next major release, other changes will go into an semi-immediate patch or minor release
For a quick PR template suggesting the right information, use one of these PR templates:
Breaking Changes/Features
Backwards-Compatible Features
Bug fixes
Documentation Changes
Test/Build/Other Changes
```

2020-09-09 09:35 UTC, MartinForReal commented
/assign @camilamacedo86

2020-09-09 09:53 UTC, MartinForReal commented
Hi @camilamacedo86,

Thanks for your instructions~

2020-09-09 09:54 UTC, camilamacedo86 commented on testdata/project-v2-multigroup/config/certmanager/certificate.yaml
> +apiVersion: cert-manager.io/v1
v2 projects still been updated. It means that we are changing its template when we should not.

2020-09-09 09:55 UTC, camilamacedo86 commented on pkg/plugin/v2/scaffolds/internal/templates/kustomize.go
> +#    version: v1
See ^ we can just perform the change inside of `pkg/plugin/v3`. Could you please revert the changes on `pkg/plugin/v2` and re-run the make generate?

2020-09-09 09:56 UTC, camilamacedo86 commented
/ok-to-test

2020-09-09 10:22 UTC, camilamacedo86 commented
It shows ok now. Great work. Also, I checked in https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/ and has not breaking changes that which would need to be addressed here.

2020-09-09 10:23 UTC, camilamacedo86 commented on testdata/project-v2-multigroup/config/certmanager/certificate.yaml
> +apiVersion: cert-manager.io/v1
Solved. Feel free to close this one.

2020-09-09 10:24 UTC, camilamacedo86 commented on pkg/plugin/v2/scaffolds/internal/templates/kustomize.go
> +#    version: v1
Solved. Feel free to close this one.

2020-10-17 10:05 UTC, camilamacedo86 commented on test/e2e/v3/e2e_suite.go
> +
it should not be added here. See; https://github.com/kubernetes-sigs/kubebuilder/blob/9406d91733acdf05cbb18d96bfe4733748af1202/test/e2e/utils/test_context.go#L30

We need to update it in the utils.

2020-10-17 10:06 UTC, camilamacedo86 commented on test/e2e/v3/e2e_suite.go
> +
@MartinForReal ^

2020-11-10 18:48 UTC, estroz commented on test/e2e/v3/e2e_suite.go
> +const certmanagerURL = "https://github.com/jetstack/cert-manager/releases/download/%s/cert-manager-legacy.yaml"
@MartinForReal you'll be able to customize which set of manifests to use (current vs legacy) with [kubectl version](https://github.com/kubernetes-sigs/kubebuilder/pull/1644/files#diff-5f5cf1a838c4d92e543721d2697ea0e2b0cf57b9f9a3c72bc9fa51a030bc56b8R80) once #1644 is merged.

2020-11-17 14:48 UTC, camilamacedo86 commented on test/e2e/utils/test_context.go
>  const prometheusOperatorURL = "https://raw.githubusercontent.com/coreos/prometheus-operator/release-%s/bundle.yaml"
We need to keep this one and then, in the e2e tests for the v3-alpha we should use the upper version and for the v2+ we should keep using this one.

2020-11-18 16:50 UTC, closed without merging