replace deprecated function LoggerTo() from zap package
kubernetes-sigs/kubebuilder pull request #1692
Opened 2020-09-23 19:07 UTC by antcs

* **Deprecated**: `func LoggerTo(destWriter io.Writer, development bool) logr.Logger`
* Will use the new function instead: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/zap/zap.go#L42

2020-09-23 19:13 UTC, antcs commented
I signed it

2020-09-24 11:06 UTC, camilamacedo86 commented on pkg/plugin/v2/scaffolds/internal/templates/controller/controller_suitetest.go
> +	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))
we cannot change the v2. Only the v3 n this case.

2020-09-24 11:10 UTC, camilamacedo86 requested changes
Really tks for your contribution 🥇. It is great. Following some needs:
- Do the change only for v3
- Assign yourself to CLA. See: https://github.com/kubernetes-sigs/kubebuilder/pull/1692#issuecomment-697906562
-  The title should have the mojo `:sparkles:` . See: https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#pr-process. Also, could you add `(only v3+)` as well?
- Changes in the scaffolds requires we update the testdata dir. It is done by running the makefile target `make generate`.

2020-09-24 15:39 UTC, antcs commented
@camilamacedo86 Hopefully all requests are satisfied.

2020-09-25 07:01 UTC, gabbifish commented
/ok-to-test

2020-09-25 09:49 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-17-0
/test pull-kubebuilder-e2e-k8s-1-15-3

2020-09-25 09:50 UTC, camilamacedo86 approved these changes
/approve

Great work 👍

2020-09-25 17:51 UTC, gabbifish commented
/approve

2020-09-28 17:00 UTC, antcs commented
@gabbifish @camilamacedo86 The lgtm label is missing here. Who will add it to the pull request? I would assume not me as I opened the pr.

2020-10-01 06:29 UTC, gabbifish commented
/lgtm

Thank you for your patience here! :)

2020-10-01 07:15 UTC, gabbifish commented
/test pull-kubebuilder-e2e-k8s-1-15-3
--

2020-10-01 07:35 UTC, gabbifish commented
/test pull-kubebuilder-e2e-k8s-1-16-2

2020-10-01 14:00 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-16-2

2020-10-01 14:44 UTC, merged

2020-10-02 00:12 UTC, DirectXMan12 commented
hmmm... somehow this missed a generated file: https://travis-ci.org/github/kubernetes-sigs/kubebuilder/jobs/732111307.