✨ Add the subcommand concept
kubernetes-sigs/kubebuilder pull request #1748
Opened 2020-10-28 09:33 UTC by Adirio

# Description
Add the subcommand concept to represent the actual operations returned by plugins.

# Motivation
Previously, both the getters and the execution objects were called plugins, leading to missunderstandings. By adding the subcommand concept now both types are well defined and their usage is more clear.

2020-10-28 09:33 UTC, Adirio commented
@estroz We talked about this yesterday, what do you think of this approach?

2020-10-28 10:34 UTC, camilamacedo86 requested changes
Hi @Adirio, 

The [plugins](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1.md) design whcih was introduced following the concept of a Plug-in Architecture.  Then, it means that operations can be extending whcih allows other tools to use 1..N plugins as also they have its own plugins.  

Then, the next step that we have been discussed is the `plugin phase 2` which has the purpose to allow us to aggregate and/or customize the plugins. For example, we might have a plugin to it the project that will do a scaffold with a layout A and also another one which will create a project with a layout B and both can be used.  

See [here](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/operator-sdk/cli/cli.go#L58-L68) how the SDK CLI call all plugins currently.  Note that in the PROJET file we write all plugins that were used to generate the files. (currently, we have just: go, ansible., helm).
 
For a further understand and follow up this WIP see; https://github.com/kubernetes-sigs/kubebuilder/issues/1378. Note that an EP will be raised based on the discussions made on this issue as well. 

In this way, I'd like to recommend you first raise an EP and/or at least an issue where you will describe: what is the problem with the current design that you would like to solve? What are the [user stories](https://en.wikipedia.org/wiki/User_story) that you would like to address  E.g `As a <role> I can <capability>, so that <receive benefit>`? Describe the technical details with examples of usage as well whcih clarifies your motivations and ideas?  

By looking at the PR shows that you are changing the plugins for each one be describe as subcommand then, it shows that goes against the purpose and architecture adopted for it.

2020-10-28 14:18 UTC, Adirio commented
Hi @camilamacedo86,

This PR follows the same design you mention, it is just a rebranding or name change.

To refer to these names I'm going to use the `X -> Y` notation, where the term in the left (`X`) is the struct that has the `GetXxxxxPlugin` methods and the term in the right (`Y`) is the struct returned by these methods.

Right now, both are called `Plugin` (`Plugin -> Plugin`). I was talking with @estroz and having both with the same name leads to missunderstandings, so we thought that one of them should be renamed (just changing the name, the implementation and design behind it stays the same).

There are two options:
1. Changing the left term: `SomethingElse -> Plugin`
2. Changing the right term: `Plugin -> SomethingElse`

The word "plugin" is already extensively used in the code (comments, variable names, ...) to refer to the left term, so I figured that it would be easier to go for the second option (`Plugin -> SomethingElse`).

When deciding which name to use, I saw how the base class for the right term structs was already `GenericSubcommand` and it basically represents that, with methods to bind flags and execute the command, so I opted for `Subcommand` (`Plugin -> Subcommand`).

Is the motivation of these change (just renaming) clearer now?

2020-10-28 17:36 UTC, estroz reviewed
These name changes make sense to me on a high level. Haven't thoroughly gone through this PR yet.

2020-10-28 17:49 UTC, camilamacedo86 commented
Hi @Adirio, 

So, by reading your comment in https://github.com/kubernetes-sigs/kubebuilder/pull/1748#issuecomment-717964428 I understand that you are doing a "cleanup" with some renames then:
- Since you rename the plugin names which are exported it is breaking change for who is consuming the plugin could you please add update the title 
- Could you please update the first comment to clarifies this PR? Note that, `Add the subcommand concept to represent the actual operations returned by plugins.` lead to belive it introduces a new design to the cli when you are doing renames mainly only. I mean, what means `Add the subcommand concept`? May something such as; 

>**Description**
> // Add a summary of what was done here specifically. E.g
> - Rename .. to ... 
> - add validation for ... 
>**Motivation**
>// Why this change is required? What are the problems that are solved with it? User story usually is helpful as well to get the motivation.

2020-10-29 06:17 UTC, Adirio commented
@camilamacedo86 Title, description and motivation updated.

2020-11-04 06:38 UTC, Adirio commented
Ping @camilamacedo86 and @estroz

2020-11-04 17:53 UTC, estroz commented on pkg/plugin/interfaces.go
> +type InitPlugin interface {
To avoid stuttering with the package name, how about
```suggestion
type Init interface {
```
Ditto elsewhere

2020-11-04 17:55 UTC, estroz commented on pkg/cli/cmd_helpers.go
>  func runECmdFunc(
Although unrelated, this function should be
```suggestion
func runEditCmdFunc(
```

2020-11-04 17:57 UTC, estroz requested changes
Looks good, just one nit about naming.

2020-11-04 18:20 UTC, camilamacedo86 approved these changes
It shows great for me now either 👍 
just address the @estroz nit https://github.com/kubernetes-sigs/kubebuilder/pull/1748#pullrequestreview-523601955 for we are able to get it merged

/approve

2020-11-04 19:57 UTC, estroz commented
/lgtm

2020-11-05 06:38 UTC, merged