🌱  refactoring hash function to global template funcs
kubernetes-sigs/kubebuilder pull request #1812
Opened 2020-11-11 01:14 UTC by christopherhein

This change was sparked from the conversation on #722 see https://github.com/kubernetes-sigs/kubebuilder/pull/1790/files#r518340728 for the suggestion.

This moves a reused func to the global funcmap to reduced the need to copy it a third time for 

Signed-off-by: Chris Hein <me@chrishein.com>

2020-11-11 01:30 UTC, christopherhein commented
/assign @Adirio

2020-11-11 01:30 UTC, christopherhein commented
/assign @camilamacedo86

2020-11-11 05:06 UTC, estroz requested changes
Just one nit

2020-11-11 05:06 UTC, estroz commented on pkg/model/file/funcmap.go
> +		"hash":  hash,
Nit: specify that this is a non-cryptographic hash function, for clarity's sake
```suggestion
		"hashFNV":  hashFNV,
```

2020-11-11 05:06 UTC, estroz commented on pkg/model/file/funcmap.go
> +func hash(s string) (string, error) {
```suggestion
func hashFNV(s string) (string, error) {
```

2020-11-11 08:40 UTC, Adirio approved these changes
/lgtm

In case you apply @estroz suggestion, remember to modify this two entries too:

2020-11-11 08:40 UTC, Adirio commented on pkg/plugin/v2/scaffolds/internal/templates/main.go
>  		LeaderElectionID:   "{{ hash .Repo }}.{{ .Domain }}",
```suggestion
		LeaderElectionID:   "{{ hashFNV .Repo }}.{{ .Domain }}",
```

2020-11-11 08:40 UTC, Adirio commented on pkg/plugin/v3/scaffolds/internal/templates/main.go
>  		LeaderElectionID:   "{{ hash .Repo }}.{{ .Domain }}",
```suggestion
		LeaderElectionID:   "{{ hashFNV .Repo }}.{{ .Domain }}",
```

2020-11-11 22:40 UTC, christopherhein commented
Thanks @Adirio and @estroz for the review on this. I've updated it to `hashFNV`.

2020-11-12 07:29 UTC, Adirio commented
/lgtm

2020-11-12 17:34 UTC, estroz commented
/approve
/lgtm

2020-11-12 17:35 UTC, christopherhein commented
Thanks @estroz

2020-11-12 17:58 UTC, merged