:fix: remove k8s get version from the init to avoid panic issues
kubernetes-sigs/kubebuilder pull request #1883
Opened 2020-12-06 09:17 UTC by camilamacedo86

2020-12-06 09:19 UTC, camilamacedo86 commented on test/e2e/utils/test_context.go
>  		BinaryName: binaryName,
Just revert the change made in: https://github.com/kubernetes-sigs/kubebuilder/commit/ea3a94a97ad4ba0cb148e711095530286d050d54#diff-7b614da29899d7d7eb4aa3b60ed598604da518c4f2dd1e6af954c942fb1c3dc3 and keep the k8sVersion

2020-12-07 16:55 UTC, estroz commented
Can you describe why you wouldn’t want cluster version lookup in the constructor? This will only panic if cluster version isn’t available (no running cluster), which is a nice fail-early check. There’s a fix you can make instead of removing version lookup from the constructor.

/hold

2020-12-09 20:01 UTC, estroz requested changes
Cluster version is required by other [e2e setups steps](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/utils/test_context.go#L120), which is why the lookup exists in the constructor. `TestContext` is meant for live cluster testing, so having a running cluster requirement is reasonable.

2020-12-10 13:26 UTC, camilamacedo86 commented
Hi @estroz, 

> Cluster version is required by other e2e setups steps, which is why the lookup exists in the constructor. 

it is NOT true at all. It is ONLY required on the current tests after the changes made in https://github.com/kubernetes-sigs/kubebuilder/pull/1840 to use a different version of cert-manager. Cannot we write a test that does not use cert-manager at all? Should we not probably able to remove the K8SVersion in the future if we wish when we no longer need to run the tests against k8s versions 1.16 if it pleases us? So, how it can now be mandatory for ANY test done with TestContext?  

> TestContext is meant for live cluster testing, so having a running cluster requirement is reasonable.

The change made in https://github.com/kubernetes-sigs/kubebuilder/pull/1840 defines that TestContext can ONLY be used when is possible to get the K8SVersion which I cannot agree that is reasonable. 

All tests implemented on this repository that uses the TestContext currently runs on the cluster, however, it does not mean that TestContext can ONLY be used to run a test on Cluster and that it is its ONLY purpose. And then, can we not have an e2e tests that not run on the cluster? 

 I'd assume that it is in `test/e2e/utils` only because it has not been used outside of this directory so far which might not be the case in the future. Note that, the TestCntext could indeed be used to replace the shell scripts in [generate_testdata.sh](https://github.com/kubernetes-sigs/kubebuilder/blob/master/generate_testdata.sh) by similar we do in SDK to create the testdata samples.

**Conclusion**;  I cannot see any advantage and value by adding this limitation whcih in POV is actually an issue added on https://github.com/kubernetes-sigs/kubebuilder/pull/1840 or at least a bad practice to start to make mandatory values that not are really required for ANY and ALL possible tests scenarios on the constructor to the test stack.

2021-01-30 03:09 UTC, closed without merging