:sparkles: Add the unit tests for HasWebhook
kubernetes-sigs/kubebuilder pull request #1909
Opened 2020-12-15 20:23 UTC by prafull01

**Description**
Add the HasWebhook() unit tests to improve the coverage.

**Motivation**
Follow up of the PR #1903 where the HasWebhook() function is introduced.

2020-12-15 20:25 UTC, prafull01 commented
/test pull-kubebuilder-e2e-k8s-1-17-0

2020-12-15 20:25 UTC, prafull01 commented
/cc @camilamacedo86

2020-12-15 20:31 UTC, prafull01 commented
/test pull-kubebuilder-e2e-k8s-1-17-0

2020-12-15 22:21 UTC, camilamacedo86 commented on pkg/model/config/config_test.go
> +		It("should return false when config has a webhook with the GVK", func() {
```suggestion
		It("should return false when config has NOT a webhook with the GVK", func() {
```

2020-12-16 05:23 UTC, prafull01 commented on pkg/model/config/config_test.go
> +		It("should return false when config has a webhook with the GVK", func() {
Done

2020-12-16 08:32 UTC, Adirio requested changes
Some english related comments:

2020-12-16 08:32 UTC, Adirio commented on pkg/model/config/config_test.go
> +		It("should return true when config has a webhook with the GVK", func() {
```suggestion
		It("should return true when config has a webhook for the GVK", func() {
```

2020-12-16 08:32 UTC, Adirio commented on pkg/model/config/config_test.go
> +		It("should return false when config NOT has a webhook with the GVK", func() {
Any of the following options:
```suggestion
		It("should return false when config does not have a webhook for the GVK", func() {
```
```suggestion
		It("should return false when config has no webhook for the GVK", func() {
```

2020-12-16 09:09 UTC, prafull01 commented
> Some english related comments:

@Adirio Fixed those.

2020-12-16 09:35 UTC, camilamacedo86 commented
Hi @prafull01,

All fine here. Since we are only adding tests the correct mojo is: `Infra/Tests/Other: 🌱 (:seedling:)`.
I will update it for we are able to merge this one.

2020-12-16 09:35 UTC, camilamacedo86 approved these changes
/approve
/lgtm

2020-12-16 09:36 UTC, merged