🐛 Use correct file name in the comments of `[kind]_types.go`
kubernetes-sigs/kubebuilder pull request #1927
Opened 2020-12-30 15:56 UTC by south37

## WHY (= Motivation)
> ### What broke (please include exact error messages if you can) 
> When we use `$ kubebuilder create api`, it generates a file like `[kind]_types.go`. In this file, there is a comment that indicates which file to change when adding a field.
> 
> However, the file name in the comment is different from the generated file name. This difference can confuse people.
> 
> The example is shown below.
> 
> ```console
> $ kubebuilder create api --group webapp --version v1 --kind Guestbook
> Create Resource [y/n]
> y
> Create Controller [y/n]
> y
> Writing scaffold for you to edit...
> api/v1/guestbook_types.go
> controllers/guestbook_controller.go
> Running make:
> $ make
> $PATH/.go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
> go fmt ./...
> go vet ./...
> go build -o bin/manager main.go
> kubebuilder create api --group webapp --version v1 --kind Guestbook  6.82s user 5.43s system 153% cpu 7.959 total
> ```
> 
> ```console
> $ cat api/v1/guestbook_types.go | grep 'Edit Guestbook_types\.go'
>         // Foo is an example field of Guestbook. Edit Guestbook_types.go to remove/update
> ```
> 
> In the above example, `Guestbook_types.go` is written in a comment. This is different from the correct file name `guestbook_types.go`.
> 
> ### What did you expect to happen?  What do you think went wrong? 
> 
> A comment should use a correct file name. In the above example, `guestbook_types.go` should be used.

cf. [The correct file name should be used in the comments of `[kind]_types.go` #1925](https://github.com/kubernetes-sigs/kubebuilder/issues/1925)

## WHAT (= A description of the change)
Fixed the comments in `[kind]_types.go`. The file names in the comments are now correct.

To be more specific, I updated the following files.

- pkg/model/file/mixins.go
- pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go
- pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go

Then executed `$ make generate`. This execution updated the mock data used in the e2e test.

Fixes #1925

2021-01-04 06:42 UTC, Adirio requested changes
Templates already have access to the `lower` function, don't need to mess with mixins for this. Revert the changes in `pkg/model/file/mixins.go` and apply the changes below. The resulting `testdata` folder should be the same as in this PR.

2021-01-04 06:42 UTC, Adirio commented on pkg/plugins/golang/v2/scaffolds/internal/templates/api/types.go
> +	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ .LoweredResourceKind }}_types.go to remove/update
```suggestion
	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ lower .Resource.Kind }}_types.go to remove/update
```

2021-01-04 06:42 UTC, Adirio commented on pkg/plugins/golang/v3/scaffolds/internal/templates/api/types.go
> +	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ .LoweredResourceKind }}_types.go to remove/update
```suggestion
	// Foo is an example field of {{ .Resource.Kind }}. Edit {{ lower .Resource.Kind }}_types.go to remove/update
```

2021-01-04 06:43 UTC, Adirio commented
/ok-to-test

2021-01-04 10:38 UTC, south37 commented
@Adirio 
Thanks for your kind comments! 😄 
I reverted the previous commit ( https://github.com/kubernetes-sigs/kubebuilder/pull/1927/commits/aaba479061cbd225d9ac6cb4309970a2d4b32a7a ) and applied the suggested changes! 💡

2021-01-04 10:54 UTC, south37 commented
[CI / Verify testdata directory (pull_request)](https://github.com/kubernetes-sigs/kubebuilder/pull/1927/checks?check_run_id=1643199148) seems to have failed due to the fact that it is now 2021 🙈 
Should I add a commit to fix this? Or should I wait until the master is fixed?

```
.
.
.
git diff testdata
diff --git a/testdata/project-v2-addon/api/v1/admiral_types.go b/testdata/project-v2-addon/api/v1/admiral_types.go
index b2a0b75..843fbe3 100644
--- a/testdata/project-v2-addon/api/v1/admiral_types.go
+++ b/testdata/project-v2-addon/api/v1/admiral_types.go
@@ -1,5 +1,5 @@
 /*
-Copyright 2020 The Kubernetes authors.
+Copyright 2021 The Kubernetes authors.
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
.
.
.
```

cf. https://github.com/kubernetes-sigs/kubebuilder/runs/1643192980#step:5:1224

2021-01-05 04:40 UTC, prafull01 reviewed
@south37 Thanks for your contribution. I have raised a #1929 for fixing the year in testdata. You need to rebase this branch with master once that PR gets merged.

Also, can you please squash all your commits into 1 commit..

2021-01-05 06:17 UTC, south37 commented
@prafull01
Thanks for your kind comment! 💡 OK, I'll wait for that PR to be merged.
I also squashed all my commits into 1 commit!

2021-01-05 21:32 UTC, Adirio approved these changes
/lgtm

/hold
Holding until the 2021 copyright gets fixed

2021-01-06 04:58 UTC, south37 commented
https://github.com/kubernetes-sigs/kubebuilder/pull/1929 was merged to master branch, so I rebased this branch! 💡

2021-01-06 05:40 UTC, prafull01 commented
/approve
/lgtm

2021-01-06 05:41 UTC, prafull01 approved these changes

2021-01-06 10:50 UTC, south37 commented
> You can assign the PR to them by writing `/assign @pwittrock` in a comment when ready.

OK.
/assign @pwittrock

2021-01-06 19:50 UTC, camilamacedo86 reviewed
/approve

2021-01-06 19:51 UTC, camilamacedo86 commented
The 2020/2021 is fixed already it shows fine to get merged. So
/hold cancel

2021-01-06 19:53 UTC, merged

2021-01-07 02:57 UTC, south37 commented
Thank you for your kind review! 😄