✨ Support argument based cross-compilation and multi-platform Dockerfile
kubernetes-sigs/kubebuilder pull request #2197
Opened 2021-05-29 15:17 UTC by aayushrangwala

Support the multi-platform cross-compilation Dockerfile in scaffolding.

- Added the --platform flag as input in the docker build command in scaffold Makefile with default value as local

- Changed Dockerfile to use BUILDPLATFORM, TARGETPLAFORM, TARGETOS and TARGETARCH in-built env var to build arg based binary

Signed-off-by: Ayush Rangwala <arangwala@vmware.com>

Motivation: Since the Kubebuilder scaffolding always generate `GOOS=linux` and `GOARCH=amd64` based Dockerfile, which results in broken image for other environments.

Fixes #2175

2021-05-30 18:36 UTC, camilamacedo86 reviewed
/ok-to-test

it seems fine for me. @estroz @jmrodri wdyt

2021-06-01 16:46 UTC, estroz requested changes
`--platform` is a [docker buildx](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) feature and will not work with vanilla `docker build` (unless a new docker release added support that I do not know about).

2021-06-10 13:17 UTC, anthr76 commented
Hi @aayushrangwala will this support a single fat manifest?

2021-09-08 21:14 UTC, anthr76 commented
/remove-lifecycle stale

2021-10-02 11:34 UTC, camilamacedo86 commented
HI @aayushrangwala, 

I hope that is fine we close this PR based on the comment:  https://github.com/kubernetes-sigs/kubebuilder/pull/2197#pullrequestreview-673358884

However, please feel free to contact us and reach out if you think that should be re-opened.

2022-08-02 14:24 UTC, camilamacedo86 commented on pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go
> +DOCKER_BUILDKIT=1
>  Buildx builds using the BuildKit engine and does not require DOCKER_BUILDKIT=1

Not required according to the docs; https://docs.docker.com/build/buildx/

2022-09-07 13:28 UTC, closed without merging