Must include Dockerfile in declarative plugin
kubernetes-sigs/kubebuilder pull request #2318
Opened 2021-08-29 16:34 UTC by justinsb

We need to copy the channels directory in the Dockerfile.

2021-08-29 18:47 UTC, justinsb commented
APIDiff looks to be a false-failure.

2021-09-07 12:46 UTC, justinsb commented
@camilamacedo86 should I try to work around the APIDIff incompatible changes on the Plugin?  I don't think this API is user-facing.

2021-10-02 09:55 UTC, camilamacedo86 commented
Hi @justinsb, 

Could you please rebase it with the master and run make generate for we are able to check?
I think that the problem here is that this PR is not synced. 

Also, feel free to ping me in the slack when it passes it the tests for we are able to move forward.

2021-10-02 09:59 UTC, camilamacedo86 requested changes
Hi @justinsb,

The contribution is great 🥇 Just a few nits. 

See that, the declarative plugin is used to scaffold apis. See: https://book.kubebuilder.io/plugins/plugins.html#plugins

Example:

```
kubebuider create api [options] --plugins=go/v3,declarative/v1
```

So, if it requires changes into the Dockerfile we need to ensure that these changes will be performed on the create API subcommand as well. 

Also, we need to add the scaffolds inside of the scaffold dir. 

Could you please check it out?

2021-12-14 01:46 UTC, camilamacedo86 commented on pkg/plugins/golang/declarative/v1/init.go
> +func (p *initSubcommand) Scaffold(fs machinery.Filesystem) error {
The scaffold would need to be in inside of the scaffold dir

2021-12-14 01:49 UTC, camilamacedo86 commented on pkg/plugins/golang/declarative/v1/plugin.go
>  func (p Plugin) GetCreateAPISubcommand() plugin.CreateAPISubcommand { return &p.createAPISubcommand }
The declarative plugin is called via `create api --plugin' so its implementation shows not accurate. 
Should we not be implementing it in the create API subcommand?

2022-02-23 00:10 UTC, camilamacedo86 commented
We can close this one since we could address this changes in : https://github.com/kubernetes-sigs/kubebuilder/pull/2507
c/c @justinsb please feel free to check and let us know if it is missing something

2022-02-23 00:10 UTC, closed without merging