(:bug:) include group name in crd patches and rbac editor/viewer files
kubernetes-sigs/kubebuilder pull request #2500
Opened 2022-01-30 18:46 UTC by rmb938

Modification to include the group name in the crd patch and rbac editor/viewer file names. This is to prevent file naming conflicts when multiple groups have the same kind names.

This is to fix #2495

2022-01-30 19:00 UTC, rmb938 commented
I've split the commits into actual code changes vs test data being re-generated. Hopefully it makes it easier to review :)

2022-01-31 21:09 UTC, camilamacedo86 commented
/ok-to-test
/lgtm

2022-01-31 21:10 UTC, camilamacedo86 commented
/lgtm cancel

2022-01-31 21:11 UTC, camilamacedo86 commented on pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/patches/enablecainjection_patch.go
> +		f.Path = filepath.Join("config", "crd", "patches", "cainjection_in_%[group]_%[plural].yaml")
```suggestion
		if f.MultiGroup {
			f.Path = filepath.Join("config", "crd", "patches", "cainjection_in_%[group]_%[plural].yaml")
		} else {
			f.Path = filepath.Join("config", "crd", "patches", "cainjection_in_%[plural].yaml")
		}
```

2022-01-31 21:12 UTC, camilamacedo86 commented on pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/patches/enablewebhook_patch.go
> +		f.Path = filepath.Join("config", "crd", "patches", "webhook_in_%[group]_%[plural].yaml")
```suggestion
                if f.MultiGroup {
			f.Path = filepath.Join("config", "crd", "patches", "webhook_in_%[group]_%[plural].yaml")
		} else {
			f.Path = filepath.Join("config", "crd", "patches", "webhook_in_%[plural].yaml")
		}

2022-01-31 21:13 UTC, camilamacedo86 commented on pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/crd_editor_role.go
> +		f.Path = filepath.Join("config", "rbac", "%[group]_%[kind]_editor_role.yaml")
```suggestion
                 if f.MultiGroup {
			f.Path = filepath.Join("config", "rbac", "%[group]_%[kind]_editor_role.yaml")
		} else {
			f.Path = filepath.Join("config", "rbac", "%[kind]_editor_role.yaml")
		}
		
```

2022-01-31 21:13 UTC, camilamacedo86 commented on pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/rbac/crd_viewer_role.go
> +		f.Path = filepath.Join("config", "rbac", "%[group]_%[kind]_viewer_role.yaml")
```suggestion
                 if f.MultiGroup {
			f.Path = filepath.Join("config", "rbac", "%[group]_%[kind]_viewer_role.yaml")
		} else {
			f.Path = filepath.Join("config", "rbac", "%[kind]_viewer_role.yaml")
		}
		
```

2022-01-31 21:15 UTC, camilamacedo86 requested changes
Thank you for the terrific collab 🥇 
Just a nit. We need to only change the path/name when is multigroup. 
Could you please:
- Apply the suggestions
- Run make generate
- Push the changes in 1 commit ( squashed )

For we are able to get these ones merged
Thank you a lot.

2022-01-31 23:34 UTC, rmb938 commented
/retest

2022-01-31 23:51 UTC, rmb938 commented
ok @camilamacedo86 All the changes are done and tests have passed. Let me know if there's anything else!

2022-02-01 10:11 UTC, camilamacedo86 approved these changes
Thank you for the great contribution 🥇 

/lgtm
/approved

2022-02-01 10:12 UTC, merged