:seedling: fix run unit test and and coverage test by removing the race flag
kubernetes-sigs/kubebuilder pull request #2581
Opened 2022-03-30 22:25 UTC by camilamacedo86

**Description**
:seedling: fix run unit test and and coverage test by removing the race flag

**Why?**
The tests implemented for config-gen alpha command are not working locally (mac os) with this option:

```
--- FAIL: TestNewCommand (0.02s)
    --- FAIL: TestNewCommand/testdata/componentconfig (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e2e04a]
```

2022-03-31 21:08 UTC, AlmogBaku commented
After investigating further, I found another issue that causing this:
1. `/pkg/cli/alpha/config-gen/testdata/project` is missing a go module. Creating a module there solves the problem
2. `/pkg/cli/alpha/config-gen/controller-gen-filer.go:L67` ignoring a critical issue

Since this is especially breaking since go 1.18, I'll add this fix as part of my PR

2022-03-31 21:09 UTC, AlmogBaku requested changes
After investigating further, I found another issue that causing this:
1. `/pkg/cli/alpha/config-gen/testdata/project` is missing a go module. Creating a module there solves the problem
2. `/pkg/cli/alpha/config-gen/controller-gen-filer.go:L67` ignoring a critical issue

Since this is especially breaking since go 1.18, I'll add this fix as part of my PR

2022-04-01 00:11 UTC, camilamacedo86 commented
/hold

2022-04-02 09:14 UTC, camilamacedo86 commented
/hold cancel

2022-04-02 10:45 UTC, camilamacedo86 commented
/hold 

I'd like to

2022-04-02 10:45 UTC, closed without merging