✨Setting LeaderElectionReleaseOnCancel to the Manager in scaffolded main.go
kubernetes-sigs/kubebuilder pull request #2596
Opened 2022-04-03 18:30 UTC by NikhilSharmaWe

Fixes #2593

2022-04-03 19:21 UTC, NikhilSharmaWe commented
Error logs says `vet: ./main.go:64:3: unknown field LeaderElectionReleaseOnCancel in struct literal`. Unable to understand the cause of it. The function [`NewManager`](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/main.go#L68) uses type `Options` as one of the parameters, since Options is actually `[manager.Options](https://github.com/kubernetes-sigs/controller-runtime/blob/master/alias.go#L49)` and since it has [`LeaderElectionReleaseOnCancel`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L176) type in it why this error is being displayed.

2022-04-04 06:45 UTC, AlmogBaku commented
This feature wasn't supported in the `controller-runtime:v0.6.4` which is the version that the go/v2 plugin uses - therefore, you should only patch go/v3

2022-04-04 07:21 UTC, NikhilSharmaWe commented on pkg/plugins/golang/v3/scaffolds/internal/templates/main.go
> +	// scripts to close when Manager is done and improves the performance of re-election.
@AlmogBaku All tests are passing now. Could you please review this explanation comment added before moving forward.

2022-04-04 08:02 UTC, camilamacedo86 requested changes
I think we need to discuss if this option should or NOT be added by default?
Also, what is the motivation for that?
What issue are you facing that you want to add it in the default scaffold.

See : https://github.com/kubernetes-sigs/kubebuilder/issues/2593#issuecomment-1087236601

/hold

2022-05-01 04:55 UTC, NikhilSharmaWe commented
@camilamacedo86 and @AlmogBaku Do we also need to add the comment here also https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-config/main.go#L66? How can we check that it is possible via the ComponentConfig as well (since @camilamacedo86 mentioned that this is needed for this case)?

2022-05-05 10:30 UTC, camilamacedo86 commented
Hi @NikhilSharmaWe, 

I think we also need to update the template used by the ComponentConfig option so that we will check its results in the sample. Why? Ensure that all have the same options, and follow the same standard making it easier for us to keep the project maintained.

2022-05-05 11:23 UTC, NikhilSharmaWe commented
@camilamacedo86 Are talking about adding the comment for this case as well?
https://github.com/kubernetes-sigs/kubebuilder/blob/43525de6224aa6381acf2733411ca383f46c26ce/pkg/plugins/golang/v3/scaffolds/internal/templates/main.go#L262

2022-05-05 12:15 UTC, camilamacedo86 commented
Hi @NikhilSharmaWe, 

The change shows to be here: https://github.com/kubernetes-sigs/kubebuilder/blob/019c1854f67e3bd61af5aa834a1573e6934b2e8b/pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/manager/controller_manager_config.go#L47-L57

We need to pass the option under the leader election options
That should be also commented ( since it is an yaml file to comment you will use the prefix # )
Also, it should have the same comment explanation.

2022-05-08 09:03 UTC, camilamacedo86 approved these changes
Great work 🥇 

/hold cancel

2022-05-09 13:42 UTC, everettraven approved these changes
/lgtm

2022-05-18 09:46 UTC, camilamacedo86 approved these changes
/lgtm

2022-05-18 10:43 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-14-10

2022-05-18 10:54 UTC, merged