:bug: Add external plugin arg filter funcs and add filters for "--group", "--version", "--kind"
kubernetes-sigs/kubebuilder pull request #2872
Opened 2022-08-12 10:50 UTC by jakobmoellersap

This fixes #2809 by introducing filter functions for plugin arguments. It currently includes two filter functions, one for the already existing implicit filter of "--help" and one for the GVK filter with "--group", "--version", "--kind". It is an arbitrary filter function so it can later on also support other filter requirements if necessary.

Tests are adjusted, but I added some tests for the filter functions. The existing helper Test for the Binding of Args I expanded to make use of the filter Functions as this is the use case in the actual method call in the CLI.

2022-08-12 11:12 UTC, everettraven commented
@jakobmoellersap Thanks for the contribution! 

I took a quick glance and this looks great but I'd like to dig into this a little deeper. In the meantime I will approve the tests.

/ok-to-test

2022-08-12 11:12 UTC, camilamacedo86 commented
/ok-to-test

The code shows fine. But for this one, I would like to ask @everettraven and @rashmigottipati to give it a look since they were more involved with it.

2022-08-12 11:38 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-19-16

2022-08-15 13:28 UTC, everettraven requested changes
Just a really minor nit in the test that should be fixed so there isn't any confusion if the test case fails. 

Other than that it looks great! Thanks @jakobmoellersap !

2022-08-15 13:28 UTC, everettraven commented on pkg/plugins/external/external_test.go
> +			By("bindAllFlags not have bound any forbidden flag after filtering")
Minor nit:
```suggestion
			By("bindSpecificFlags not have bound any forbidden flag after filtering")
```

2022-08-15 23:39 UTC, everettraven approved these changes
Looks great! I love how it is built to be easy to extend in the future! Awesome job @jakobmoellersap !

2022-08-16 09:13 UTC, jakobmoellersap commented
Blocked by https://github.com/kubernetes-sigs/kubebuilder/issues/2878

2022-08-17 18:16 UTC, everettraven commented
@jakobmoellersap #2879 was merged. If you rebase with master it should kick off the checks again with the updated action.

2022-08-18 13:21 UTC, everettraven reviewed
/lgtm

2022-08-18 13:23 UTC, everettraven commented
@jakobmoellersap I'm not an approver so I can't add the approved label. 

@camilamacedo86 would you mind giving this another look?

/cc @camilamacedo86

2022-08-23 03:38 UTC, camilamacedo86 approved these changes
I think we can move with this one

/approved

2022-08-23 03:49 UTC, merged