web-hook doc added
kubernetes-sigs/kubebuilder pull request #3159
Opened 2023-01-14 23:40 UTC by impact-maker

Description
Added the web-hook documentation

Motivation
There was no webhook documentation for branch book-b1

2023-01-14 23:42 UTC, impact-maker reviewed
Reviewed webhook.md

2023-01-15 11:44 UTC, AlmogBaku requested changes

2023-01-15 11:44 UTC, AlmogBaku commented on docs/book/src/cronjob-tutorial/ running-webhook.md 
> +You need follow this to install the cert manager bundle.
it's probably worth mentioning an savvier solution such as
https://github.com/open-policy-agent/cert-controller

2023-01-15 11:50 UTC, AlmogBaku commented
Hi @impact-maker,
Thank you for your contribution!

Please see my comments above :)

2023-01-15 18:12 UTC, camilamacedo86 requested changes
We should not change the v1 docs. It is a legacy doc regards an ancient version 1.x+
The docs referent to the current version 3.X are in https://book.kubebuilder.io/quick-start.html.

2023-01-23 10:16 UTC, closed without merging

2023-02-25 02:37 UTC, Sajiyah-Salat commented
I think this pr was closed just because he was adding things in book v1 instead of v3. right?