📖 [docs] : corrected layout of manually_migration_guide_gov3_to_gov4.md
kubernetes-sigs/kubebuilder pull request #3176
Opened 2023-01-20 15:05 UTC by swastik959

* the markdown formatting of the file manually_migration_guide_gov3_to_gov4.md was incorrect hence leading to a bad layout
especially in the last section .

* it fixes the issue #3167

* feel free to point out any discrepancy

2023-01-20 17:06 UTC, everettraven requested changes
@swastik959 Thanks for your contribution! I have a couple suggestions:

2023-01-20 17:27 UTC, swastik959 commented on docs/book/src/migration/manually_migration_guide_gov3_to_gov4.md
> +
@everettraven 
thanks for the feedback 
you can check it now

2023-01-20 17:50 UTC, camilamacedo86 approved these changes
/lgtm

Could you please sign the CLA for we move forward?

2023-01-21 00:51 UTC, swastik959 commented
> /lgtm
> 
> Could you please sign the CLA for we move forward?

@camilamacedo86 I have signed it please guide me through further process

2023-01-21 01:22 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-24-7

2023-01-21 01:23 UTC, camilamacedo86 commented
/ok-to-test

2023-01-21 02:47 UTC, swastik959 commented
> @swastik959: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name | Commit | Details | Required | Rerun command
> --- | --- | --- | --- | ---
> pull-kubebuilder-e2e-k8s-1-25-3 | 9b697130099db14d0aca0e0489df652bb6d2c631 | [link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubebuilder/3176/pull-kubebuilder-e2e-k8s-1-25-3/1616607375442055168) | true | `/test pull-kubebuilder-e2e-k8s-1-25-3`
> 
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes-sigs&repo=kubebuilder&pr=3176). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aswastik959). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes-sigs/kubebuilder/issues?q=is:issue+is:open) when you hit one in your PR.
> 
> <details>
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
> </details>
> <!-- test report -->

@camilamacedo86  this test case failed can you please look into it

2023-01-21 05:35 UTC, swastik959 commented
/test pull-kubebuilder-e2e-k8s-1-25-3

2023-01-21 05:56 UTC, merged