🐛 Clarify deprecate documentation for API methods which are served to work with CRD/WebHook API versions v1beta1
kubernetes-sigs/kubebuilder pull request #3261
Opened 2023-03-06 16:40 UTC by varshaprasad96

These deprecation messages will reappear in the next release wherein go/v3 is deprecated in favor of go/v4. Till then these warnings are not necessary.

Please refer here: https://github.com/operator-framework/helm-operator-plugins/actions/runs/4342983995/jobs/7584462203#step:6:52 - for users with KB 3.9.0, these warnings are unnecessary. They should be re-introduced in the KB version which has go/v3 deprecated.

2023-03-06 16:41 UTC, rashmigottipati approved these changes
/lgtm

2023-03-06 16:47 UTC, camilamacedo86 requested changes
/hold

The comments make clear that the API is deprecated as it should be.
The errors faced in the helm plugin are in the linters.
Where you use the deprecated methods you must ignore the linter check with // nolint: structcheck

2023-03-06 17:33 UTC, camilamacedo86 approved these changes
/lgtm

2023-03-06 17:40 UTC, varshaprasad96 commented
Merging this with the release branch after CI passes, since I had originally created it against `release-3.9`. Will do that same for master in follow up

2023-03-06 18:29 UTC, camilamacedo86 commented
/hold cancel

2023-03-06 18:55 UTC, camilamacedo86 commented
@varshaprasad96 we need to also cherry-pick it against master

2023-03-06 22:57 UTC, camilamacedo86 commented
/retest tide

2023-03-06 22:58 UTC, camilamacedo86 approved these changes

2023-03-07 09:19 UTC, merged

2023-03-08 16:58 UTC, varshaprasad96 commented
/cherrypick master