:bug: patchesStrategicMerge to patches.
kubernetes-sigs/kubebuilder pull request #3374
Opened 2023-04-30 02:02 UTC by Sajiyah-Salat

Fixes #3372 

 See that the default scaffolds:

Warning:
'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run
"kustomize edit fix' to update
your Kustomization automatically.

Therefore I replaced patchesStrategicMerge by patches in the kustomize/v2 templates code.

2023-04-30 02:10 UTC, Sajiyah-Salat commented
I have run make generate. why its failing?

2023-04-30 06:40 UTC, NikhilSharmaWe commented on pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
> +patches:
@Sajiyah-Salat Try to make this change again in an up-to-date branch (upstream/master) and run `make generate`. After running `make generate` you will see that these files are also updated:
- docs/book/src/component-config-tutorial/testdata/project/config/crd/kustomization.yaml
- pkg/plugins/common/kustomize/v2/scaffolds/internal/templates/config/crd/kustomization.go
- testdata/project-v4-config/config/crd/kustomization.yaml
- testdata/project-v4-declarative-v1/config/crd/kustomization.yaml
- testdata/project-v4-multigroup/config/crd/kustomization.yaml
- testdata/project-v4-with-deploy-image/config/crd/kustomization.yaml
- testdata/project-v4/config/crd/kustomization.yaml

then commit the changes.

2023-05-02 04:35 UTC, NikhilSharmaWe commented
@Sajiyah-Salat It seems fine now.
Could you please squash the commits?

2023-05-02 11:54 UTC, Sajiyah-Salat commented
```
$git push
To https://github.com/Sajiyah-Salat/kubebuilder.git
 ! [rejected]          sajiyah#3372 -> sajiyah#3372 (non-fast-forward)
error: failed to push some refs to 'https://github.com/Sajiyah-Salat/kubebuilder.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
squashing always comes with frustration. I have squashed the commits. i have tried pulling as well. still its giving the following error

2023-05-03 06:51 UTC, NikhilSharmaWe commented
Seems fine now
/approve

2023-05-04 06:44 UTC, camilamacedo86 requested changes
Thank you for your contribution.
- Please, remove [oryxBuildBinary](https://github.com/kubernetes-sigs/kubebuilder/pull/3374/files#diff-0cc91448cff3c23248ec636a288566167dae94ade2b69d8aaaa24e9c6a12db6a)
- Also, after the change in the boilerplate, the samples under testdata and docs should be automatically updated by running `make generate`
- Also, we have a standard for the titles because they will be used to generate the release notes. So, in this case I am changing the title of this PR accordingly so that you can better check it and I hope that you do not mind.

**Note** Details about this review: https://github.com/kubernetes-sigs/kubebuilder/pull/3374/files#r1181174158

> Please, ensure that you read the [Contributing](https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md) to know how to contribute with the project. Also, feel free to contribute to this doc if you see that it is missing or has outdated info.

2023-05-08 09:28 UTC, camilamacedo86 submitted a review, later dismissed
That is great 🥇 
Thank you for the contribution 🚀 

See that testdata CI is falling because it seems that docs are not successfully update.
Note that:
- You must to run `make generate` after you do the changes
- You must have in your local environment your fork cloned in the same module path as described here in the contributing guide : https://github.com/kubernetes-sigs/kubebuilder/blob/master/CONTRIBUTING.md#how-to-build-kubebuilder-locally . So that when you run `make install` a binary build from the source code will be added to your GOPATH/bin and when you run `make generate` it will regenerate the samples under testdata and docs samples using it. 

Also, ensure that you have your branch updated (rebased) with the master.

2023-05-08 13:08 UTC, Sajiyah-Salat commented
The mistake I did is I deleted oryxBuildBinary and directly pushed it to branch without running make generate. Now when I run make generate and git status it says everything is upto date. What to do?

2023-05-09 05:01 UTC, lauchokyip commented
> @Sajiyah-Salat This might be because your local branch is not up to date with the origin branch.
> 
> Try this:
> 
> 1. git fetch origin
> 2. git reset --hard origin/sajiyah#3372
> 3. git reset commitID-of-last-commit-before-yours
> 4. git add .
> 5. git commit -m "patchesStrategicMerge to patches"

@NikhilSharmaWe `git reset --hard` is not a good practice should be avoided because it will erase your whole history
@Sajiyah-Salat Please checkout this guide to learn about Git Workflow (https://www.kubernetes.dev/docs/guide/github-workflow/)

2023-05-09 07:07 UTC, NikhilSharmaWe commented
@lauchokyip Yes, I understand that but just wanted @Sajiyah-Salat to make the correct changes with simplicity, just for this case.

2023-05-10 13:54 UTC, Sajiyah-Salat commented
I think the tests have some issues. I have run make generate. Following files suggested by @NikhilSharmaWe Changed as well. Still its failing. Why?

2023-05-10 14:54 UTC, camilamacedo86 commented
HI @Sajiyah-Salat,

Did you have your branch rebased with master?
Can you try: 

1 _ update the master branch

$ git checkout master
$ git pull upstream master # I do not know how did you set the git to looking for the remote source. I use upstream


2 - rebase with your branch

$ git checkout <your branch>
$ git rebase master

3 - run make install # It will ensure that you have the bin with the source code changes
4 - run make generate # It will generate the samples under testdata and docs

2023-05-11 05:25 UTC, camilamacedo86 approved these changes
Great @Sajiyah-Salat !!!!

/approved
/lgtm

2023-05-11 05:38 UTC, Sajiyah-Salat commented
wooh.... after a long time. Thank you for guiding me through out.

2023-05-11 05:39 UTC, merged