logs info updated
kubernetes-sigs/kubebuilder pull request #3512
Opened 2023-07-31 03:28 UTC by Sajiyah-Salat

There was same logs at different place which results in difficulty to debug. 
Updated the unique logs to give better understanding.
Partially fixes: #3435

2023-07-31 19:06 UTC, camilamacedo86 commented
/pull-kubebuilder-e2e-k8s-1-25-3

2023-08-02 07:23 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-25-3

2023-08-03 13:26 UTC, Kavinjsir approved these changes
lgtm 👍🏼

2023-08-08 07:29 UTC, camilamacedo86 requested changes
@Sajiyah-Salat 

Can you please squash the commits for we are able to move forward?

2023-08-08 22:30 UTC, varshaprasad96 reviewed
Just a nit, looks good after squashing the commits!
Nice work @Sajiyah-Salat

2023-08-08 22:30 UTC, varshaprasad96 commented on hack/docs/internal/cronjob-tutorial/generate_cronjob.go
> +	CheckError("updating suite_test.go to test cleanup", err)
Nit:
```suggestion
	CheckError("updating suite_test.go to cleanup tests", err)
```

2023-08-09 01:56 UTC, Sajiyah-Salat commented
Hello @camilamacedo86 Just a small request. I have squash the commits. If still there is any changes require let me know we will start a new pr for that. Just merge this one. As yo know I have squashing issues a lot.

2023-08-10 12:32 UTC, camilamacedo86 approved these changes
/lgtm

/approved

/hold cancel

2023-08-10 12:32 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-26-0

2023-08-14 14:45 UTC, camilamacedo86 commented
/test pull-kubebuilder-e2e-k8s-1-26-0

/skip netlify/kubebuilder/deploy-preview

2023-08-15 13:05 UTC, camilamacedo86 reviewed
Moving forward with this one since it is blocked by the preview of docs which is an issue that we are sorting out in another PR and has no relation with this one.

2023-08-15 13:05 UTC, merged