🌱 fix kustomization yaml's comments about patches file names
kubernetes-sigs/kubebuilder pull request #3580
Opened 2023-09-03 10:40 UTC by lowang-bh

Fixes #3502

The comments about path of patch file name in `config/crd/kustomization.yaml` is not correct when enable multigroup

<img width="894" alt="image" src="https://github.com/kubernetes-sigs/kubebuilder/assets/21003791/203b776e-08bd-4cd4-9678-6a0535ba2113">

2023-09-03 11:46 UTC, camilamacedo86 commented on pkg/plugins/common/kustomize/v1/scaffolds/internal/templates/config/crd/kustomization.go
>  	resourceCodeFragment = `- bases/%s_%s.yaml
Thank you for the contribution

The kustomize/v1 is only used in the deprecated layouts
It is deprecated as well.

So, we should only fix it in the kustomize/v2

Could you please remove the change from this file?

2023-09-03 11:50 UTC, camilamacedo86 requested changes
Thank you for the contribution 🥇 

Just a few nits:

- We should only change kustomize/v2 ( v1 is deprecated )
- We need to run make generate after the changes so that the samples are updated
- Please, ensure that after the changes you have only one commit ( squash them out ) so that we can get it merged

PS.: Note that I changed the title for we have a better info for the release notes. I hope that you do not mind.

2023-09-03 11:50 UTC, camilamacedo86 commented
/ok-to-test

2023-09-03 14:34 UTC, lowang-bh commented
> Just a few nits:
> 
> * We should only change kustomize/v2 ( v1 is deprecated )
> * We need to run make generate after the changes so that the samples are updated
> * Please, ensure that after the changes you have only one commit ( squash them out ) so that we can get it merged

Got it.

2023-09-04 07:19 UTC, camilamacedo86 approved these changes
Great 👍 

I am happy that you check that we should only use the group in the name for multi-group layouts.

2023-09-04 07:19 UTC, camilamacedo86 reviewed
/lgtm

2023-09-04 07:37 UTC, merged