✨ feat(go/v4): add support for custom boilerplate path
kubernetes-sigs/kubebuilder pull request #3716
Opened 2023-12-21 17:31 UTC by ardikabs

> Related to #3697 

## Description

Add support to a custom boilerplate path for the `base.go.kubebuilder.io/v4` plugin.

The following are changes involved in this feature request:
1. add `--boilerplatePath` flag to `kubebuilder --plugin "base.go.kubebuilder.io/v4" init`
2. add `--boilerplatePath` flag to `kubebuilder --plugin "base.go.kubebuilder.io/v4" create api`
3. add `--boilerplatePath` flag to `kubebuilder --plugin "base.go.kubebuilder.io/v4" create webhook`

## Expectation

After applying this feature, you can customize the boilerplate file path to any path other than the default (`hack/boilerplate.go.txt`), like the following examples:

* `Init`
```bash
kubebuilder init --plugins base.go.kubebuilder.io/v4 --license apache2 --owner example.com --boilerplatePath tools/hack/boilerplate.go.txt
```

* `Create API`
```bash
kubebuilder create api --controller=false --group example --kind CustomPlugin --version v1alpha1 --boilerplatePath tools/hack/boilerplate.go.txt
```

* `Create Webhook`
```bash
kubebuilder create webhook --group example --kind CustomPlugin --version v1alpha1 --defaulting --programmatic-validation --boilerplatePath tools/hack/boilerplate.go.txt
```

2023-12-21 17:40 UTC, ardikabs commented
As I am new to the kubebuilder codebase, please be advised on where I should put a test for this feature. Thanks!

2023-12-29 19:16 UTC, camilamacedo86 requested changes
The change cannot be made within the API command. Doing so would mean that we would be able to define a different value for each API.

If we allow customization, it must be done via the kubebuilder init and kubebuilder edit commands. Additionally, the path must be stored in the PROJECT file.

Could you please take a look at it and see if you have any concerns?

2024-01-02 14:23 UTC, varshaprasad96 commented
+1 to what @camilamacedo86 mentioned. Allowing boilerplate configured differently during these commands would lead to confusion of:
(1) Single project having multiple licenses.
(2) Certain commands like `create webhook` also modify existing files - causing conflict on boilerplate usage.
Though (1) is still possible, its a scenario where user can manually change the boilerplate based on their needs as it seems to be an edge case.

2024-02-06 08:05 UTC, camilamacedo86 commented
> As I am new to the kubebuilder codebase, please be advised on where I should put a test for this feature. Thanks!

See the e2e tests: https://github.com/kubernetes-sigs/kubebuilder/tree/master/test/e2e

To create the tests that would be new dir with a test like the others just to check the layout after the change.
Following the steps that I see here: 

- create a project kb init --header-file-path=<path>
- then, ensure that the hack/dir is not created and instead the new path
- after that, ensure that the makefile is updated accordingly
- Call generated and ensured that the header of the files had the header of the path informed. 
Lastly, it is properly configured in the ProjectConfig via a new spec.

2024-02-26 07:59 UTC, camilamacedo86 commented
Hi @ardikabs 

I am closing this one since, as we spoke if we would like to add this feature, we need to add it for the init|edit subcommand and keep the data stored in the PROJECT file so that it can be used across since it is valid for the whole project. We cannot have one specific config for each API.

Therefore, I hope that you do not mind if we close this one, and please feel free to raise a new PR with the proposed solution or reopen this one.

2024-02-26 07:59 UTC, closed without merging