:bug:  Bump controller-tools.
kubernetes-sigs/kubebuilder pull request #3793
Opened 2024-02-20 12:22 UTC by mneverov

Bump controller-gen to fix NPE.
Fixes #3792.

I ran `make generate` but commented regenerating [scaffold v2](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/generate.sh#L136) because v2 uses ancient controller-tools v0.3.0 with incompatible features.

2024-02-20 16:23 UTC, camilamacedo86 commented on pkg/plugins/golang/v3/scaffolds/init.go
> +	ControllerToolsVersion = "v0.14.0"
We should not change go/v3. It is deprecated and will be soon no longer supported
More info: https://github.com/kubernetes-sigs/kubebuilder/discussions/3622

2024-02-20 16:25 UTC, camilamacedo86 requested changes
Note that you should do the bump for go/v4 only
Then, run make generate to get the docs and samples update
Also, we should have only 1 commit per PR

So, can you please review the changes made?

2024-02-20 18:47 UTC, mneverov commented
> for go/v4 only

hi @camilamacedo86, go/v4 does already have [proper controller version](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/init.go#L38).
If `v3` is obsolete then there is nothing to do. The workaround is not to use go v1.22 until `go/v4` is released.
Should I close the PR?

2024-02-20 21:04 UTC, camilamacedo86 commented
Hi @mneverov 

> hi @camilamacedo86, go/v4 does already have [proper controller version](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v4/scaffolds/init.go#L38).
If v3 is obsolete then there is nothing to do. The workaround is not to use go v1.22 until go/v4 is released.
Should I close the PR?

I will try to push a new release ASAP. Can you give me a couple of days?
Also, the next kubebuilder release will still not support go v1.22 
Unless prior to that, we bump controller-runtime using v1.22, the go/v4 to use it as all places that now you can find 1.21.
PS.: You can check previous PRs to add support to go versions to know what we need to bump.

2024-02-21 17:45 UTC, camilamacedo86 commented
Hi @mneverov 

Sorry, now I checked this one.

- See that the latest release has the bump of controller-tools already: https://github.com/kubernetes-sigs/kubebuilder/blob/v3.14.0/testdata/project-v4/Makefile#L167
- We will NOT bump it for the legacy layout go/v3 because this one is deprecated for a long period and will be removed asap and we will do a MAJOR release see: https://github.com/kubernetes-sigs/kubebuilder/discussions/3622


**Now, regarding support to go 1.22.**

It is NOT supported yet by Kubebuilder.
Note that we support the versions which are scaffolded by default with the tool.
You can change as you please, but then we cannot ensure that things are still working since the changes will result in combinations not tested by us. See from the doc: https://book.kubebuilder.io/quick-start#versions-and-supportability

![Screenshot 2024-02-21 at 17 43 07](https://github.com/kubernetes-sigs/kubebuilder/assets/7708031/b09e3d07-926e-47cb-b557-736e8fec27f0)

**What we need to do to support go 1.22**
- Wait for controller-runtime and controller-tools releases using go 1.22
- Then, change the go plugin to scaffold go 1.22 and use it
- Mainly replace all places across the project that have 1.21 with 1.22

Therefore, I am closing this one as deferred and I hope that the info provided clarifies why and you do not mind it.
Anyway, please feel free to re-open or open new issues/prs as you see fit.

Your help is very welcome. 

Cheers,

2024-02-21 17:45 UTC, closed without merging